#!/usr/bin/env bash
#
# Show the terminal color palette in different ways.
# Copyright (C) 2018,2019 Carlos Zubieta
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function _color_pacman() {
    # Based on: http://crunchbang.org/forums/viewtopic.php?pid=144481#p144481
    echo -e "\033[0;33m  ▄███████▄                \033[0;31m  ▄██████▄    \
\033[0;32m  ▄██████▄    \033[0;34m  ▄██████▄    \033[0;35m  ▄██████▄    \
\033[0;36m  ▄██████▄\033[0m"
    echo -e "\033[0;33m▄█████████▀▀               \033[0;31m▄\033[0;37m█▀█\
\033[0;31m██\033[0;37m█▀█\033[0;31m██▄  \033[0;32m▄█\033[0;37m███\033[0;32m██\
\033[0;37m███\033[0;32m█▄  \033[0;34m▄█\033[0;37m███\033[0;34m██\033[0;37m███\
\033[0;34m█▄  \033[0;35m▄█\033[0;37m███\033[0;35m██\033[0;37m███\033[0;35m█▄  \
\033[0;36m▄██\033[0;37m█▀█\033[0;36m██\033[0;37m█▀█\033[0;36m▄\033[0m"
    echo -e "\033[0;33m███████▀      \033[0;37m▄▄  ▄▄  ▄▄   \033[0;31m█\
\033[0;37m▄▄█\033[0;31m██\033[0;37m▄▄█\033[0;31m███  \033[0;32m██\033[0;37m█ █\
\033[0;32m██\033[0;37m█ █\033[0;32m██  \033[0;34m██\033[0;37m█ █\033[0;34m██\
\033[0;37m█ █\033[0;34m██  \033[0;35m██\033[0;37m█ █\033[0;35m██\033[0;37m█ █\
\033[0;35m██  \033[0;36m███\033[0;37m█▄▄\033[0;36m██\033[0;37m█▄▄\033[0;36m█\
\033[0m"
    echo -e "\033[0;33m███████▄      \033[0;37m▀▀  ▀▀  ▀▀   \
\033[0;31m████████████  \033[0;32m████████████  \033[0;34m████████████  \
\033[0;35m████████████  \033[0;36m████████████\033[0m"
    echo -e "\033[0;33m▀█████████▄▄               \033[0;31m██▀██▀▀██▀██  \
\033[0;32m██▀██▀▀██▀██  \033[0;34m██▀██▀▀██▀██  \033[0;35m██▀██▀▀██▀██  \
\033[0;36m██▀██▀▀██▀██\033[0m"
    echo -e "\033[0;33m  ▀███████▀                \033[0;31m▀   ▀  ▀   ▀  \
\033[0;32m▀   ▀  ▀   ▀  \033[0;34m▀   ▀  ▀   ▀  \033[0;35m▀   ▀  ▀   ▀  \
\033[0;36m▀   ▀  ▀   ▀\033[0m"
    echo
    echo -e "\033[1;33m  ▄███████▄                \033[1;31m  ▄██████▄    \
\033[1;32m  ▄██████▄    \033[1;34m  ▄██████▄    \033[1;35m  ▄██████▄    \
\033[1;36m  ▄██████▄\033[0m"
    echo -e "\033[1;33m▄█████████▀▀               \033[1;31m▄\033[1;37m█▀█\
\033[1;31m██\033[1;37m█▀█\033[1;31m██▄  \033[1;32m▄█\033[1;37m█ █\033[1;32m██\
\033[1;37m█ █\033[1;32m█▄  \033[1;34m▄█\033[1;37m█ █\033[1;34m██\033[1;37m█ █\
\033[1;34m█▄  \033[1;35m▄█\033[1;37m█ █\033[1;35m██\033[1;37m█ █\033[1;35m█▄  \
\033[1;36m▄██\033[1;37m█▀█\033[1;36m██\033[1;37m█▀█\033[1;36m▄\033[0m"
    echo -e "\033[1;33m███████▀      \033[1;37m▄▄  ▄▄  ▄▄   \033[1;31m█\
\033[1;37m▄▄█\033[1;31m██\033[1;37m▄▄█\033[1;31m███  \033[1;32m██\033[1;37m███\
\033[1;32m██\033[1;37m███\033[1;32m██  \033[1;34m██\033[1;37m███\033[1;34m██\
\033[1;37m███\033[1;34m██  \033[1;35m██\033[1;37m███\033[1;35m██\033[1;37m███\
\033[1;35m██  \033[1;36m███\033[1;37m█▄▄\033[1;36m██\033[1;37m█▄▄\033[1;36m█\
\033[0m"
    echo -e "\033[1;33m███████▄      \033[1;37m▀▀  ▀▀  ▀▀   \
\033[1;31m████████████  \033[1;32m████████████  \033[1;34m████████████  \
\033[1;35m████████████  \033[1;36m████████████\033[0m"
    echo -e "\033[1;33m▀█████████▄▄               \033[1;31m██▀██▀▀██▀██  \
\033[1;32m██▀██▀▀██▀██  \033[1;34m██▀██▀▀██▀██  \033[1;35m██▀██▀▀██▀██  \
\033[1;36m██▀██▀▀██▀██\033[0m"
    echo -e "\033[1;33m  ▀███████▀                \033[1;31m▀   ▀  ▀   ▀  \
\033[1;32m▀   ▀  ▀   ▀  \033[1;34m▀   ▀  ▀   ▀  \033[1;35m▀   ▀  ▀   ▀  \
\033[1;36m▀   ▀  ▀   ▀\033[0m"
}

function _color_grid() {
    # Source: http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html
    local T='gYw' # The test text
    echo -e "\n                 40m     41m     42m     43m\
     44m     45m     46m     47m"
    for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
        '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
        '  36m' '1;36m' '  37m' '1;37m'; do
        local FG=${FGs// /}
        echo -en " $FGs \033[$FG  $T  "
        for BG in 40m 41m 42m 43m 44m 45m 46m 47m; do
            echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m"
        done
        echo
    done
    echo
}

function _true_color_line() {
    # Based on: https://gist.github.com/XVilka/8346728
    local blue red green arr=("/" "\\\\")
    for blue in {0..255}; do
        red=$((255 - blue))
        green=$((blue * 2))
        if [ $green -gt 255 ]; then
            green=$((511 - green))
        fi
        echo -n -e "\033[48;2;${red};${green};${blue}m"
        echo -n -e "\033[38;2;$((255 - red));$((255 - green));$((255 - blue))m"
        echo -n -e "${arr[((blue % 2))]}\033[0m"
    done
    echo
}

function _colors_list() {
    echo -e "\033[0mNC (No color)"
    echo -e "\033[1;37mWHITE\t\033[0;30mBLACK"
    echo -e "\033[0;34mBLUE\t\033[1;34mLIGHT_BLUE"
    echo -e "\033[0;32mGREEN\t\033[1;32mLIGHT_GREEN"
    echo -e "\033[0;36mCYAN\t\033[1;36mLIGHT_CYAN"
    echo -e "\033[0;31mRED\t\033[1;31mLIGHT_RED"
    echo -e "\033[0;35mPURPLE\t\033[1;35mLIGHT_PURPLE"
    echo -e "\033[0;33mYELLOW\t\033[1;33mLIGHT_YELLOW"
    echo -e "\033[1;30mGRAY\t\033[0;37mLIGHT_GRAY"
}

function _colors_space() {
    # Based on: http://crunchbang.org/forums/viewtopic.php?pid=126921%23p126921#p126921
    echo -e "\033[0;30m  ▀▄   ▄▀     \033[0;31m ▄▄▄████▄▄▄    \
\033[0;32m  ▄██▄     \033[0;33m  ▀▄   ▄▀     \033[0;34m ▄▄▄████▄▄▄    \
\033[0;35m  ▄██▄  \033[0m"
    echo -e "\033[0;30m ▄█▀███▀█▄    \033[0;31m███▀▀██▀▀███   \
\033[0;32m▄█▀██▀█▄   \033[0;33m ▄█▀███▀█▄    \033[0;34m███▀▀██▀▀███   \
\033[0;35m▄█▀██▀█▄\033[0m"
    echo -e "\033[0;30m█▀███████▀█   \033[0;31m▀▀███▀▀███▀▀   \
\033[0;32m▀█▀██▀█▀   \033[0;33m█▀███████▀█   \033[0;34m▀▀███▀▀███▀▀   \
\033[0;35m▀█▀██▀█▀\033[0m"
    echo -e "\033[0;30m▀ ▀▄▄ ▄▄▀ ▀   \033[0;31m ▀█▄ ▀▀ ▄█▀    \
\033[0;32m▀▄    ▄▀   \033[0;33m▀ ▀▄▄ ▄▄▀ ▀   \033[0;34m ▀█▄ ▀▀ ▄█▀    \
\033[0;35m▀▄    ▄▀\033[0m"
    echo
    echo -e "\033[1;30m▄ ▀▄   ▄▀ ▄   \033[1;31m ▄▄▄████▄▄▄    \
\033[1;32m  ▄██▄     \033[1;33m▄ ▀▄   ▄▀ ▄   \033[1;34m ▄▄▄████▄▄▄    \
\033[1;35m  ▄██▄  \033[0m"
    echo -e "\033[1;30m█▄█▀███▀█▄█   \033[1;31m███▀▀██▀▀███   \
\033[1;32m▄█▀██▀█▄   \033[1;33m█▄█▀███▀█▄█   \033[1;34m███▀▀██▀▀███   \
\033[1;35m▄█▀██▀█▄\033[0m"
    echo -e "\033[1;30m▀█████████▀   \033[1;31m▀▀▀██▀▀██▀▀▀   \
\033[1;32m▀▀█▀▀█▀▀   \033[1;33m▀█████████▀   \033[1;34m▀▀▀██▀▀██▀▀▀   \
\033[1;35m▀▀█▀▀█▀▀\033[0m"
    echo -e "\033[1;30m ▄▀     ▀▄    \033[1;31m▄▄▀▀ ▀▀ ▀▀▄▄   \
\033[1;32m▄▀▄▀▀▄▀▄   \033[1;33m ▄▀     ▀▄    \033[1;34m▄▄▀▀ ▀▀ ▀▀▄▄   \
\033[1;35m▄▀▄▀▀▄▀▄\033[0m"
    echo
    echo -e "                                   \033[1;37m▌\033[0m"
    echo
    echo -e "                                 \033[1;37m▌\033[0m"
    echo
    echo -e "                            \033[1;37m    ▄█▄    \033[0m"
    echo -e "                            \033[1;37m▄█████████▄\033[0m"
    echo -e "                            \033[1;37m▀▀▀▀▀▀▀▀▀▀▀\033[0m"
}

function _colors_help() {
    echo "Show the color palette of the terminal in different forms."
    echo
    echo "Usage: colors [-hlgtps]"
    echo
    echo " -h  This help"
    echo " -l  Show a list of color names"
    echo " -g  Show a grid of colors"
    echo " -t  Show a true color line"
    echo " -p  Show a colored pacman"
    echo " -s  Show a colored space invaders"
}

if ! args=$(getopt hlgtps "$*"); then
    _colors_help
    exit 2
fi

# shellcheck disable=SC2086
set -- $args

for i; do
    case "$i" in
    -h)
        _colors_help
        shift
        break
        ;;
    -l)
        _colors_list
        shift
        break
        ;;
    -g)
        _color_grid
        shift
        break
        ;;
    -t)
        _true_color_line
        shift
        break
        ;;
    -p)
        _color_pacman
        shift
        break
        ;;
    --)
        _colors_space
        shift
        break
        ;;
    esac
done
