#!/usr/bin/env bash
# Usage: viscosity [command] [vpn]
#
# Connect/disconnect from a VPN using Viscosity.app on OS X.
#
# Help:
#   viscosity list                  List all VPNs
#   viscosity connect               Connect to all VPNs
#   viscosity connect "My VPN"      Connect to the VPN named "My VPN"
#   viscosity disconnect            Disconnect from all VPNs
#   viscosity disconnect "My VPN"   Disconnect from the VPN named "My VPN"
#   viscosity status                Show connection status for all VPNs
#   viscosity status "My VPN"       Show connection status of the VPN named "My VPN"
#   viscosity help                  Show this help message
#
# Adapted from: https://josh.fail/blog/2015/viscosity-cli.html

[[ "${DEBUG}" ]] && set -x

case "${1}" in
  ""|-h|--help|help)
    sed -ne '/^#/!q;s/.\{1,2\}//;1d;p' < "${0}"
    exit
    ;;
  connect|disconnect)
    if [[ -z "${2}" ]]; then
      osascript -e "tell application \"Viscosity\" to ${1}all"
    else
      osascript -e "tell application \"Viscosity\" to ${1} \"${2}\""
    fi
    ;;
  status)
    if [[ "${2}" ]]; then
      osascript -e "tell application \"Viscosity\" to return state of (connections where name is \"${2}\")"
    else
      osascript -e '
        tell application "Viscosity"
          set output to ""
          set i to 0
          repeat with _conn in connections
            set i to i + 1
            set _vpn to name of _conn
            set _state to state of _conn
            set output to output & _vpn & ": " & _state
            if i < count of connections
              set output to output & "\n"
            end if
          end repeat
          output
        end tell
      '
    fi
    ;;
  list)
    osascript -e '
      tell application "Viscosity"
        set output to ""
        set i to 0
        repeat with _conn in connections
          set i to i + 1
          set _name to name of _conn
          set output to output & _name
          if i < count of connections
            set output to output & "\n"
          end if
        end repeat
        output
      end tell
    '
    ;;
  --completion)
    case "${2}" in
      bash)
        printf "_viscosity() {
    case \${COMP_CWORD} in
        1)
            COMPREPLY=(\$(compgen -W \"help list connect disconnect status\" -- \"\$2\"))
            ;;
        2)
            COMPREPLY=()
            case \"\$3\" in
                connect|disconnect|status)
                    local vpn
                    while IFS= read -r vpn; do
                        COMPREPLY+=(\"\$(printf \"%%q\" \"\$vpn\")\")
                    done < <(IFS=$'\\\\n' compgen -W \"\$(viscosity list)\" -- \"\$2\")
                    ;;
            esac
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}
complete -F _viscosity viscosity
"
        ;;
      zsh)
        printf "_viscosity () {
        _arguments '1: :(help connect disconnect status list)' '2:: :->vpn'
        case \$line[1] in
                (connect | disconnect | status) local -a array
                        array=(\${(f)\"\$(viscosity list)\"})
                        compadd -a array ;;
        esac
}
compdef _viscosity viscosity
"
        ;;
      *)
        exit 1
        ;;
    esac
    ;;
  *)
    echo "Invalid command ${1}"
    exit 1
    ;;
esac

